TEXTS = {
    'ua': {
        'choose_lang': "🇺🇦 Оберіть мову:\n🇬🇧 Choose your language:",
        'welcome': "👋 Надішліть будь-який файл як *Документ* — я запропоную, що з ним зробити.\n\n📌 Доступні операції:\n  ⚡ *Стисло* — ключові метадані\n  📋 *Повний* — усі метадані\n  🛡 *C2PA* — перевірка AI-маркування\n  🧹 *Очистити* — видалити метадані\n\n🛑 /cancel — скасувати поточну операцію\n\n_Важливо: файли надсилайте через Файл → Документ, не як фото/відео._",
        'btn_short': "⚡ Стисло",
        'btn_full': "📋 Повний",
        'btn_c2pa': "🛡 C2PA",
        'btn_clean': "🧹 Очистити",
        'btn_clean_ai': "🧹 Видалити AI-маркування",
        'btn_yes': "✅ Так, видалити",
        'btn_no': "❌ Скасувати",
        'file_too_big': "❌ Файл перевищує ліміт Telegram API (20 МБ).",
        'what_to_do': "📎 `{name}`  ·  {size}\n\nЩо зробити з файлом?",
        'lang_set': "✅ Мову змінено на Українську!",
        'wait': "⏳ Дочекайтеся завершення поточної операції або натисніть /cancel.",
        'compressed': "⚠️ Telegram стиснув файл і видалив метадані.\nНадішліть його через *Файл → Документ*.",
        'cancelled': "🛑 Операцію скасовано.",
        'already_running': "⏳ Вже виконується операція!",
        'file_old': "❌ Файл застарів. Надішліть знову.",
        'confirm_clean': "⚠️ Метадані файлу `{name}` будуть видалені *безповоротно*.\n\nПродовжити?",
        'short_report': "⚡ Стислий звіт щодо метаданих.",
        'full_report': "📋 Повний звіт щодо метаданих.",
        'c2pa_found': "🛡 *C2PA-маркування знайдено*\n\n{summary}",
        'c2pa_report': "📄 Повний C2PA-звіт",
        'c2pa_clean_ask': "Бажаєте видалити AI-маркування з файлу?",
        'c2pa_not_found': "✅ *AI-маркування не знайдено*\n\nФайл не містить C2PA-маніфесту або він був видалений.",
        'clean_success': "✅ Всі метадані видалено.",
        'clean_partial': "✅ Метадані видалено (частина службових тегів відео збережена — це норма).",
        'send_again': "Надішліть файл знову, щоб переконатися в результаті.",
        'timeout': "⏱ Таймаут. Спробуйте ще раз.",
        'no_exiftool': "❌ exiftool не знайдено в системі.",
        'error': "❌ Помилка: {error}",
        'extract_failed': "⚠️ Не вдалося витягти метадані.",
        'more_actions': "Ще щось зробити з цим файлом?"
    },
    'en': {
        'choose_lang': "🇺🇦 Оберіть мову:\n🇬🇧 Choose your language:",
        'welcome': "👋 Send any file as a *Document* — I'll suggest what to do with it.\n\n📌 Available operations:\n  ⚡ *Short* — key metadata\n  📋 *Full* — all metadata\n  🛡 *C2PA* — AI-watermark check\n  🧹 *Clean* — remove metadata\n\n🛑 /cancel — abort current operation\n\n_Note: send files via File → Document, not as photo/video._",
        'btn_short': "⚡ Short",
        'btn_full': "📋 Full",
        'btn_c2pa': "🛡 C2PA",
        'btn_clean': "🧹 Clean",
        'btn_clean_ai': "🧹 Remove AI-watermark",
        'btn_yes': "✅ Yes, delete",
        'btn_no': "❌ Cancel",
        'file_too_big': "❌ File exceeds Telegram API limit (20 MB).",
        'what_to_do': "📎 `{name}`  ·  {size}\n\nWhat to do with the file?",
        'lang_set': "✅ Language set to English!",
        'wait': "⏳ Please wait for the current operation to finish or press /cancel.",
        'compressed': "⚠️ Telegram compressed the file and removed metadata.\nSend it via *File → Document*.",
        'cancelled': "🛑 Operation cancelled.",
        'already_running': "⏳ An operation is already running!",
        'file_old': "❌ File is too old. Send it again.",
        'confirm_clean': "⚠️ Metadata of `{name}` will be deleted *permanently*.\n\nContinue?",
        'short_report': "⚡ Short metadata report.",
        'full_report': "📋 Full metadata report.",
        'c2pa_found': "🛡 *C2PA-watermark found*\n\n{summary}",
        'c2pa_report': "📄 Full C2PA report",
        'c2pa_clean_ask': "Do you want to remove the AI-watermark from the file?",
        'c2pa_not_found': "✅ *AI-watermark not found*\n\nFile doesn't contain a C2PA manifest or it was removed.",
        'clean_success': "✅ All metadata removed.",
        'clean_partial': "✅ Metadata removed (some service tags kept — this is normal).",
        'send_again': "Send the file again to verify the result.",
        'timeout': "⏱ Timeout. Try again.",
        'no_exiftool': "❌ exiftool not found in the system.",
        'error': "❌ Error: {error}",
        'extract_failed': "⚠️ Failed to extract metadata.",
        'more_actions': "Anything else to do with this file?"
    }
}